// As you start writing your guide, keep everything between BEGIN and END in the README.adoc,
// meaning delete anything else that is above or below the BEGIN and END lines inclusively.
// Also, please delete any instructions that begin with //--** after you read them
// ----------- BEGIN -----------
//--** INSTRUCTION: The copyright statement must appear at the top of the file
// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide-multipane
//--** INSTRUCTION: The project id is the part of the git repository after the guide- and must be specified
//--** :projectid: github repo name without the `guide-` prefix
:projectid: codeengine-http
//--** INSTRUCTION: Provide an estimate of how long the guide will take to go through.
:page-duration: 45 minutes
//--** INSTRUCTION: Provide the date when the guide is published.  Format is YYYY-MM-DD.
:page-releasedate: 2022-12-12
//--** INSTRUCTION: Provide a description for the guide index page.
:page-description: Learn how to create a system and an inventory serverless applications, using Jakarta Restful Web Services, Open Liberty, Docker and IBM Cloud Code Engine.
:page-tags: ['MicroProfile', 'Docker', 'Cloud']
:page-related-guides: ['rest-intro', 'docker']
//--** INSTRUCTION: Set 'basic', 'microprofile', 'none'

//--** INSTRUCTION: Specify the slug in the website. This must be unique.
:page-permalink: /guides/{projectid}
//--** INSTRUCTION: Source the common page elements, clone `git@github.com:OpenLiberty/guides-common.git`.
:common-includes: ../guides-common/
//--** INSTRUCTION: Source the image directory to include any images for the guide.
:imagesdir: /img/guide/{codeengine-http}
//--** INSTRUCTION: Update the SEO title for the guide
:page-seo-title: Creating serverless functions in IBM Cloud Code Engine using MicroProfile applications
//--** INSTRUCTION: Update the SEO description for the guide
:page-seo-description: Find out how to create serverless functions in IBM Cloud Code Engine using MicroProfile applications
//--** INSTRUCTION: You can't have a new line between the attributes and the title.
= Creating serverless functions in IBM Cloud Code Engine using MicroProfile applications

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to use MicroProfile applications to create serverless functions in IBM Cloud Code Engine.

== What you'll learn

//--** Write about what the user will learn in a meaningful intro paragraph.
//--** Follow the intro paragraph with more details of what the user will learn, but still keep it brief.
//--** See the REST guide at as an exemplar guide.
//--** https://openliberty.io/guides/rest-intro.html
//--** https://github.com/OpenLiberty/guide-rest-intro

// EXAMPLE:
// =============================================================================
You will learn how to deploy two MicroProfile applications in Open Liberty containers, to IBM Cloud Container Registry and then to Code Engine, to run as serverless functions in IBM Cloud. You will also learn how to send and receive data from the developed serverless functions, using Http as the event source.

=== What is Serverless
Serverless is an entire stack of cloud services that can respond to specific events or requests, and scale to zero when no longer in use. With serverless provisioning, management and billing are handled by the cloud provider and invisible to developers. Developers focus on writing code and business logic, and not worry about infrastructure. Infrastructure tasks (for example provisioning, securing, scaling, scheduling, patching etc...), are the responsibilities of the cloud provider. The cloud provider spins up and provisions the required resources on demand when the code executes, and spins them down when execution stops. Developers or their companies do not have to pay for idle capacity. Pricing is based on execution time and resources required. To learn more about serverless, you can read the https://www.ibm.com/cloud/learn/serverless[What is Serverless] document.

=== What is IBM Cloud Code Engine
IBM Cloud Code Engine is a fully managed serverless platform, that runs your containerized workloads. This includes running web-apps, microservices, event driven functions, or batch jobs. Code engine can also build container images from your source code. Like any other serverless platform, code engine is designed such that developers can focus on writing code and not on infrastructure.


The two MicroProfile applications you will run as IBM Code Engine serverless functions, are called `system` and `inventory`. The `system` application returns JVM system properties of the running container. The `inventory` application queries properties from the `system` application, and adds them to its inventory list. It also queries its inventory list, to return the properties that were queried from the `system` application.

// =================================================================================================
// Prerequisites
// =================================================================================================

== Additional prerequisites

Before you begin, the following additional tools need to be installed:

* *Docker:* You need containerization software for building containers. IBM Cloud Code Engine supports Docker, so you will use Docker in this guide. For installation instructions, refer to the official https://docs.docker.com/install/[Docker^] documentation.

* *ibmcloud:* You need the IBM Cloud command-line tool `ibmcloud` to interact with your IBM Cloud account and its services. See the official https://cloud.ibm.com/docs/cli?topic=cli-getting-started[CLI Getting Started^] documentation, on how to install `ibmcloud`. +
To verify that the IBM Cloud CLI is installed correctly, run the following command:
+
[role=command]
```
ibmcloud help
```

* *ibmcloud cr:* You need the IBM Cloud Container Registry command-line tool plugin to set up your own image namespace in an IBM-hosted, and managed, private registry. You can store and share Docker images with all users in your IBM Cloud account from the registry. Refer to https://cloud.ibm.com/docs/cli?topic=cli-install-devtools-manually#idt-install-container-registry-cli-plugin[Installing IBM Cloud Container Registry CLI plug-in^], for installation instructions on how to install the plugin. +
To verify that the plugin is installed correctly, run the following command:
+
[role=command]
```
ibmcloud plugin show container-registry
```

* *ibmcloud ce:* You need the IBM Cloud Code Engine command-line tool plugin to access the Code Engine service in your IBM Cloud account. See the official documentation https://cloud.ibm.com/docs/codeengine?topic=codeengine-install-cli[Installing the Code Engine CLI plug-in^], on how to install the plugin. +
To verify that the plugin is installed correctly, run the following command:
+
[role=command]
```
ibmcloud plugin show code-engine
```
// =============================================================================


///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::{common-includes}/gitclone.adoc[]


== Granting IBM Cloud Code Engine project access to IBM Cloud Container Registry

Before you run the microprofile applications as serverless functions in IBM Cloud Code engine, you have to create a project, in which the containerized applications will run. To get the containerized applications from your local machine to the project, you have to deploy them to IBM Cloud Container Registry, and grant the created project access to the IBM Cloud Container Registry.


=== Creating an IBM Cloud API Key
Create an IBM Cloud API Key to be used by Ibm Cloud Code Engine to access images from Ibm Cloud Container Registry. It is recommended to create a different key for this purpose, so that the key is managed separately for its intended resources. Therefore, one can delete or update the key as they like, and will only need to change access for these resources, but will not need to change access to other resources which do not use this key.
----
ibmcloud iam api-key-create guideKey -d "Key to demo the open liberty serverless applications, using code engine" --file guideKey.txt
----
The api key will be stored in the `guideKey.txt` file. Save this file in a safe and protected location.

=== Creating an IBM Cloud Code Engine Project
Create an IBM Cloud Code Engine project to group the serverless functions, and thus be able to manage them and provide access to them.
----
ibmcloud ce project create --name guide-project
----
List code engine projects to check if the `guide-project` has been successfully created.
----
ibmcloud ce project list
----

=== Adding IBM Cloud Container Registry access to IBM Cloud Code Engine project
Change to the `guide-project` code engine project, to work within its context.
----
ibmcloud ce project select -n guide-project
----
Create an image registry secret, with which IBM Cloud code engine can access IBM Cloud container registry. In the command below, `<REGION>` can be for example `uk`, which is your location, and `XXXX` is the api key stored in the `guideKey.txt` file.
----
ibmcloud ce registry create --name guide-registry --server <REGION>.icr.io --username iamapikey --password XXXX
----


== Deploying microprofile applications to IBM Cloud Code Engine
In this section, you will learn how to deploy two microprofile applications in open liberty containers to IBM Cloud code engine. You will build and containerize the system and inventory applications, push them to IBM Cloud container registry, and then deploy them to your IBM Cloud code engine project.

=== Building and containerizing the applications
The first step of deploying to IBM Cloud code engine, is to build you microprofile applications and containerize them.

The starting Java project, which you can find in the `start` directory, is a multi-module Maven project. It is made up of the `system` and `inventory` applications. Each application resides in its own directory, start/guide-codeengine-http-system and start/guide-codeengine-http-inventory. Both of these directories contain a Dockerfile, which is necessary for building the Docker images. If you’re unfamiliar with Dockerfiles, check out the https://openliberty.io/guides/containerize.html[Containerizing microservices^] guide.

To build these applications, navigate to the `start` directory and run the following command:

[role=command]
```
mvn package
```

Next, run the `docker build` commands to build the container images for your application:
[role='command']
```
docker build -t system:1.0-SNAPSHOT guide-codeengine-http-system/.
docker build -t inventory:1.0-SNAPSHOT guide-codeengine-http-inventory/.
```

The `-t` flag in the `docker build` command allows the Docker image to be labeled (tagged) in the `name[:tag]` format. The tag for an image describes the specific image version. If the optional `[:tag]` tag is not specified, the `latest` tag is created by default.

During the build, you see various Docker messages that describe what images are being downloaded and built. When the build finishes, run the following command to list all local Docker images:

[role=command]
```
docker images
```

Verify that the `system:1.0-SNAPSHOT` and `inventory:1.0-SNAPSHOT` images are listed among them, for example:

[source, role="no_copy"]
----
REPOSITORY                        TAG
system                            1.0-SNAPSHOT
inventory                         1.0-SNAPSHOT
icr.io/appcafe/open-liberty       kernel-slim-java11-openj9-ubi
----

If you don't see the `system:1.0-SNAPSHOT` and `inventory:1.0-SNAPSHOT` images, then check the Maven build log for any potential errors.

=== Pushing the images to IBM Cloud Container Registry
Pushing the images to a registry, facilitates their deployment to IBM Cloud code engine.

First, you must login to IBM Cloud container registry.
[role=command]
```
ibmcloud cr login
```
To ensure that you are targeting the right IBM Cloud container registry region, run the command below. `<YOUR_REGION>` is your cloud region, for example `uk-south`.
[role=command]
```
ibmcloud cr region-set <YOUR_REGION>
```
Next, create a namespace for your docker images:
[role=command]
```
ibmcloud cr namespace-add guide-namespace
```
Next, choose repositories and tags, by which you can identify the images. `<REGION>` is your country, for example `uk`.
[role='command']
```
docker tag system:1.0-SNAPSHOT <REGION>.icr.io/guide-namespace/system:1.0-SNAPSHOT
docker tag inventory:1.0-SNAPSHOT <REGION>.icr.io/guide-namespace/inventory:1.0-SNAPSHOT
```
Next, push the images to your private registry:
[role='command']
```
docker push <REGION>.icr.io/guide-namespace/system:1.0-SNAPSHOT
docker push <REGION>.icr.io/guide-namespace/inventory:1.0-SNAPSHOT
```
Finally, verify that your images are in your private registry:
[role=command]
```
ibmcloud cr image-list
```

=== Creating serverless applications in IBM Cloud Code Engine
This is the final step of deploying your containerized applications to IBM Cloud code engine.

Change to the project in IBM Cloud code engine, in which you want to create your serverless applications:
[role=command]
```
ibmcloud ce project select -n guide-project
```

Create serverless applications in IBM Cloud code engine from your images.
[role='command']
```
ibmcloud ce app create --name systemapp --image uk.icr.io/guide-namespace/system:1.0-SNAPSHOT --registry-secret guide-registry --port 9080
ibmcloud ce app create --name inventoryapp --image uk.icr.io/guide-namespace/inventory:1.0-SNAPSHOT --registry-secret guide-registry --port 9080
```

=== Making requests to the serverless applications
To make requests to the `systemapp` and `inventoryapp` serverless applications using `curl`, you have to get their urls.
[role='command']
```
ibmcloud ce app get --name systemapp --output url
ibmcloud ce app get --name inventoryapp --output url
```
First, set `systemapp` url and `inventoryap` url as system properties, to ease making requests to them.
[role='command']
```
INVENTORY_HOST=inventoryapp.xxx111.eu-gb.codeengine.appdomain.cloud
SYSTEM_HOST=systemapp.xxx111.eu-gb.codeengine.appdomain.cloud
```
Next, execute the `GET` method on `systemapp` to get its container properties.
[role='command']
```
curl -X GET https://$SYSTEM_HOST/system/properties
```
Next, execute the `GET` method on `inventoryapp` to show that no properties from `systemapp` have been added to its inventory list.
[role='command']
```
curl -X GET https://$INVENTORY_HOST/inventory/systems
```
It returns an empty list
[source, role="no_copy"]
----
[]
----
Next, add the `systemapp` container properties `java.vendor.url`, and `wlp.install.dir` to the inventory list of `inventoryapp`.
[role='command']
```
curl -X POST https://$INVENTORY_HOST/inventory/systems/$SYSTEM_HOST -H "Ce-Specversion: 1.0" -H "Ce-Type: java.properties" -H "Ce-Source: io.cloudevents.examples/properties" -H "Ce-Id: properties" -H "Content-Type: application/json" -H "Ce-Subject: resources" -d "[\"java.vendor.url\",\"wlp.install.dir\"]"
```
Finally, retrieve the properties added to the `inventoryapp` inventory list:
[role='command']
```
curl -X GET https://$INVENTORY_HOST/inventory/systems
```


== Testing the application

//--** Show how to test your application.

// EXAMPLE:
// ======================================================================================================

[role="code_command hotspot", subs="quotes"]
----
#Create the `TodoIT` class.#
`finish/src/test/java/it/io/openliberty/guides/todo/TodoIT.java`
----

TodoIT.java
[source, Java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
include::finish/src/test/java/it/io/openliberty/guides/todolistSample/TodoIT.java[]
----

* Explain what each [hotspot=13-20]`@Test` test case is testing
* Explain key methods
// ======================================================================================================

//--** Include this for info on how to run the tests
[role='command']
include::{common-includes}/devmode-test.adoc[]

//--** Including a listing block with test results here
//--** Show console output of the test results

//--** OPTIONAL: after listing the test results, mention a simple change a user can make/introduce that
//--** will cause the tests to fail. Be brief and don't give the users all of the instructions.
//--** At this point, they should be comfortable enough to figure it out on their own.

//--** Include this for info on how to quit development mode
[role='command']
include::{common-includes}/devmode-quit.adoc[]


== Great work! You're done!

//--** Briefly summarize what the user achieved in this guide (1-2 sentences).
EXAMPLE: You have just completed building a simple todo list application using JAXRS and CDI services in Open Liberty.

//--** OPTIONAL: briefly state what the user could do next now that they've learned the
//--** technologies in this guide.

//--** Include the below from the guides-common repo to tell users how they can contribute to the guide
include::{common-includes}/attribution.adoc[subs="attributes"]

//--** DO NO CREATE ANYMORE SECTIONS AT THIS POINT
//--** Related guides will be added in automatically here if you included them in ":page-related-guides"
// ------------ END ------------





