// Copyright (c) 2023 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide-multipane
:projectid: cloud-ibm-codeengine
:page-duration: 30 minutes
:page-releasedate: 2023-01-10
:page-description: Learn how to deploy a system and an inventory microservice, using Open Liberty, Docker and IBM Cloud Code Engine.
:page-tags: ['MicroProfile', 'Docker', 'Cloud']
:page-related-guides: ['rest-intro', 'docker']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:imagesdir: /img/guide/{cloud-ibm-codeengine-http}
:page-seo-title: Deploying microservices into IBM Cloud Code Engine
:page-seo-description: Find out how to deploy microservices using IBM Cloud Code Engine
:hashtag: #
:win: WINDOWS
:mac: MAC
:linux: LINUX
:system-api: \https://systemapp.[xxxxxx].[REGION].codeengine.appdomain.cloud
:inventory-api: \https://inventoryapp.[xxxxxx].[REGION].codeengine.appdomain.cloud
:system-get: curl -X GET {system-api}/system/properties
:inventory-get: curl -X GET https://inventoryapp.[xxxxxx].[REGION].codeengine.appdomain.cloud/inventory/systems
:inventory-post: curl -X POST https://inventoryapp.[xxxxxx].[REGION].codeengine.appdomain.cloud/inventory/systems/systemapp.[xxxxxx].[REGION].codeengine.appdomain.cloud
:guide-author: Open Liberty
= Deploying microservices into IBM Cloud Code Engine

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to deploy microservices into IBM Cloud Code Engine, so that they run as serverless services.

// =================================================================================================
// Introduction
// =================================================================================================

== What you'll learn

You will learn how to deploy two microservices in containers, to https://www.ibm.com/cloud/container-registry[IBM Cloud Container Registry] and then to https://www.ibm.com/cloud/code-engine[IBM Cloud Code Engine], to run as serverless functions in IBM Cloud. You will also learn how to send and receive data from the developed serverless functions, using Http as the event source.

=== What is serverless?
Serverless is an entire stack of cloud services that can respond to specific events or requests, and scale to zero when no longer in use. With serverless provisioning, management and billing are handled by the cloud provider and invisible to developers. Developers focus on writing code and business logic, and not worry about infrastructure. Infrastructure tasks (for example provisioning, securing, scaling, scheduling, patching etc...), are the responsibilities of the cloud provider. The cloud provider spins up and provisions the required resources on demand when the code executes, and spins them down when execution stops. Developers or their companies do not have to pay for idle capacity. Pricing is based on execution time and resources required. To learn more about serverless, you can read the https://www.ibm.com/cloud/learn/serverless[What is Serverless] document.

=== What is IBM Cloud Code Engine?
IBM Cloud Code Engine is a fully managed serverless platform, that runs your containerized workloads. This includes running web-apps, microservices, event driven functions, or batch jobs. Code engine can also build container images from your source code. Like any other serverless platform, code engine is designed such that developers can focus on writing code and not on infrastructure.


The two microservices you will run as IBM Cloud Code Engine serverless functions, are called `system` and `inventory`. The `system` microservice returns JVM system properties of the running container. The `inventory` microservice queries properties from the `system` microservice, and adds them to its inventory list. It also queries its inventory list, to return the properties that are queried from the `system` microservice.

// =================================================================================================
// Prerequisites
// =================================================================================================

== Additional prerequisites

Before you begin, the following additional tools need to be installed:

* *Docker:* You need a containerization software for building containers. IBM Cloud Code Engine supports Docker, so you will use Docker in this guide. For installation instructions, refer to the official https://docs.docker.com/install/[Docker^] documentation.

* *IBM Cloud CLI:* You need the IBM Cloud command-line tool `ibmcloud` to interact with your IBM Cloud account and its services. To install the IBM Cloud CLI for your platform, run one of the following commands:


include::{common-includes}/os-tabs.adoc[]

[.tab_content.windows_section]
--
Open command prompt as an administrator and run the following command.

[role=command]
```
powershell -command "Set-ExecutionPolicy Unrestricted; iex(New-Object Net.WebClient).DownloadString('https://clis.cloud.ibm.com/install/powershell')"
```
--

[.tab_content.mac_section]
--
[role=command]
```
curl -fsSL https://clis.cloud.ibm.com/install/osx | sh
```
--

[.tab_content.linux_section]
--
[role=command]
```
curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
```
--

To verify that the IBM Cloud CLI is installed correctly, run the following command:

[role=command]
```
ibmcloud help
```

* *IBM Cloud Container Registry plug-in CLI:* 
You need the IBM Cloud Container Registry command-line tool plugin `ibmcloud cr` to set up your own image namespace in the IBM Cloud Container registry. Your container images will be pushed to the registry, enabling them to be deployed into IBM Cloud Code Engine. To install the IBM Cloud Container Registry plug-in CLI on your platform, run the following command:

[role=command]
```
ibmcloud plugin install container-registry
```

To verify that the plug-in is installed correctly, run the following command:

[role=command]
```
ibmcloud plugin show cr
```

* *IBM Cloud Code Engine plug-in CLI:*
You need the IBM Cloud Code Engine command-line tool plug-in `ibmcloud ce` to access the Code Engine service in your IBM Cloud account. To install the IBM Cloud Code Engine plug-in CLI on your platform, run the following command: 

[role=command]
```
ibmcloud plugin install code-engine
```

To verify that the plug-in is installed correctly, run the following command:

[role=command]
```
ibmcloud plugin show ce
```

// =================================================================================================
// Getting Started
// =================================================================================================

[role='command']
include::{common-includes}/gitclone.adoc[]


== Granting IBM Cloud Code Engine project access to IBM Cloud Container Registry

Before you run the microprofile microservices as serverless functions in IBM Cloud Code Engine, you have to create a project, in which the containerized microservices will run. To get the containerized microservices from your local machine to the project, you have to deploy them to IBM Cloud Container Registry, and grant the created project access to the IBM Cloud Container Registry.

=== Configuring IBM Cloud CLI
Log in to IBM Cloud by using the `ibmcloud` command line. When you are prompted to select a region, for example, choose `us-south`. This allows you to create a free cloud resources, which are limited to specific regions. Note that if you are using a federated user ID, you will have to use the `--sso` flag to get a one-time code for single sign-on.

[role=command]
```
ibmcloud login
```

=== Creating an IBM Cloud API Key
Create an IBM Cloud API Key to be used by IBM Cloud Code Engine to access images from IBM Cloud Container Registry. It is recommended to create a different key for this purpose, so that the key is managed separately for its intended resources. Therefore, one can delete or update the key as they like, and will only need to change access for these resources, but will not need to change access to other resources which do not use this key.

[role=command]
```
ibmcloud iam api-key-create guideKey -d "Key to demonstrate deploying microservices into IBM Cloud Code Engine" --file guideKey.txt
```

The api key will be stored in the `guideKey.txt` file. Save this file in a safe and protected location.

=== Creating a resource group
Use the following command to create a resource group `guide-resource-group`, to which your Cloud resources for this demo will belong:

[role=command]
```
ibmcloud resource group-create guide-resource-group
```

=== Changing to your resource group
Use the following command to change to your resource group `guide-resource-group`:

[role=command]
```
ibmcloud target -g guide-resource-group
```

=== Creating an IBM Cloud Code Engine Project
Create an IBM Cloud Code Engine project to group the serverless functions, and thus be able to manage them and provide access to them.

[role=command]
```
ibmcloud ce project create --name guide-project
```

List code engine projects to check if the `guide-project` has been successfully created.

[role=command]
```
ibmcloud ce project list
```

=== Adding IBM Cloud Container Registry access to IBM Cloud Code Engine project
Change to the `guide-project` code engine project, to work within its context.

[role=command]
```
ibmcloud ce project select -n guide-project
```

Create an image registry secret, with which IBM Cloud code engine can access IBM Cloud container registry. In the command below, `XXXX` is the api key stored in the `guideKey.txt` file.

[role=command]
```
ibmcloud ce registry create --name guide-registry --server us.icr.io --username iamapikey --password XXXX
```

// =================================================================================================
// Building and containerizing the microservices
// =================================================================================================

== Building and containerizing the microservices

The first step of deploying to IBM Cloud code engine, is to build and containerize your microservices.

The starting Java project, which you can find in the `start` directory, is a multi-module Maven project. It is made up of the `system` and `inventory` microservices. Each microservice resides in its own directory, start/guide-codeengine-http-system and start/guide-codeengine-http-inventory. Both of these directories contain a Dockerfile, which is necessary for building the Docker images. If you’re unfamiliar with Dockerfiles, check out the https://openliberty.io/guides/containerize.html[Containerizing microservices^] guide.

To build these microservices, navigate to the `start` directory and run the following command:

[role=command]
```
mvn package
```

Next, run the `docker build` commands to build the container images for your microservice:
[role='command']
```
docker build -t system:1.0-SNAPSHOT system/.
docker build -t inventory:1.0-SNAPSHOT inventory/.
```

The `-t` flag in the `docker build` command allows the Docker image to be labeled (tagged) in the `name[:tag]` format. The tag for an image describes the specific image version. If the optional `[:tag]` tag is not specified, the `latest` tag is created by default.

During the build, you see various Docker messages that describe what images are being downloaded and built. When the build finishes, run the following command to list all local Docker images:

[role=command]
```
docker images
```

Verify that the `system:1.0-SNAPSHOT` and `inventory:1.0-SNAPSHOT` images are listed among them, for example:

[source, role="no_copy"]
----
REPOSITORY                        TAG
system                            1.0-SNAPSHOT
inventory                         1.0-SNAPSHOT
icr.io/appcafe/open-liberty       kernel-slim-java11-openj9-ubi
----

If you don't see the `system:1.0-SNAPSHOT` and `inventory:1.0-SNAPSHOT` images, then check the Maven build log for any potential errors.

// =================================================================================================
// Pushing the images to IBM Cloud Container Registry
// =================================================================================================

== Pushing the images to IBM Cloud Container Registry
Pushing the images to a registry, facilitates their deployment to IBM Cloud code engine.

First, you must login to IBM Cloud container registry.
[role=command]
```
ibmcloud cr login
```
To ensure that you are targeting the right IBM Cloud container registry region, run the command below. `[REGION]` is your cloud region, for example `us-south`.
[role=command]
```
ibmcloud cr region-set [REGION]
```
Next, create a namespace for your docker images:
[role=command]
```
ibmcloud cr namespace-add guide-namespace
```
Next, choose repositories and tags, by which you can identify the images.
[role='command']
```
docker tag system:1.0-SNAPSHOT us.icr.io/guide-namespace/system:1.0-SNAPSHOT
docker tag inventory:1.0-SNAPSHOT us.icr.io/guide-namespace/inventory:1.0-SNAPSHOT
```
Next, push the images to your private registry:
[role='command']
```
docker push us.icr.io/guide-namespace/system:1.0-SNAPSHOT
docker push us.icr.io/guide-namespace/inventory:1.0-SNAPSHOT
```
Finally, verify that your images are in your private registry:
[role=command]
```
ibmcloud cr image-list
```

// =================================================================================================
// Deploying the microservices
// =================================================================================================

== Deploying the microservices in IBM Cloud Code Engine
Now that your container images are in the IBM Cloud container registry, deploy them to IBM Cloud code engine.

Change to the project in IBM Cloud code engine, in which you want to create your serverless microservices:
[role=command]
```
ibmcloud ce project select -n guide-project
```

Create serverless microservices in IBM Cloud code engine from your images.
[role='command']
```
ibmcloud ce app create --name systemapp --image us.icr.io/guide-namespace/system:1.0-SNAPSHOT --registry-secret guide-registry --port 9080
ibmcloud ce app create --name inventoryapp --image us.icr.io/guide-namespace/inventory:1.0-SNAPSHOT --registry-secret guide-registry --port 9080
```

=== Finding the microservice's url

To make requests to the `systemapp` and `inventoryapp` serverless microservices, you have to get their urls.
[role='command']
```
ibmcloud ce app get --name systemapp --output url
ibmcloud ce app get --name inventoryapp --output url
```
The urls for systemsapp and invetoryapp, which will be returned will be in the format below, whereby you will substitute `xxxxx` and `cloud region`, by the values returned by `ibmcloud ce app get`

* `{system-api}`
* `{inventory-api}`

=== Making requests to the serverless microservices

Execute the `GET` method on `systemapp` to get its container properties.
[role='command']
---
$ `{system-get}`

Next, execute the `GET` method on `inventoryapp` to show that no properties from `systemapp` have been added to its inventory list.
[role='command']
---
$ `{inventory-get}`

It returns an empty list
[source, role="no_copy"]
----
[]
----
Next, add the `systemapp` container properties `java.vendor.url`, and `wlp.install.dir` to the inventory list of `inventoryapp`.
[role='command']
---
$ `{inventory-post}` -H "Ce-Specversion: 1.0" -H "Ce-Type: java.properties" -H "Ce-Source: io.cloudevents.examples/properties" -H "Ce-Id: properties" -H "Content-Type: application/json" -H "Ce-Subject: resources" -d "[\"java.vendor.url\",\"wlp.install.dir\"]"

Finally, retrieve the properties added to the `inventoryapp` inventory list:
[role='command']
---
$ `{inventory-get}`

// =================================================================================================
// Testing microservices that are running on IBM Cloud
// =================================================================================================

== Testing microservices that are running on IBM Cloud

A few tests are included for you to test the basic functionality of the microservices. If a test fails, then you might have introduced a bug into the code. To run the tests, wait until all pods are in the ready state before proceeding further. The default properties that are defined in the `pom.xml` file are:

[cols="15, 100", options="header"]
|===
| *Property*        | *Description*
| `system.host`        | The hostname of the system service on IBM Cloud Code Engine.
| `inventory.host` | The hostname of the inventory service on IBM Cloud Code Engine.
|===

Use the following command to run the integration tests against your microservices. Substitute `[system-hostname]` and `[inventory-hostname]` with the appropriate values.

[role=command]
```
mvn failsafe:integration-test -Dsystem.host=[system-hostname] -Dinventory.host=[inventory-hostname]
```

If the tests pass, you'll see an output similar to the following for each service respectively:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointIT
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.673 sec - in it.io.openliberty.guides.system.SystemEndpointIT

Results:

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.inventory.InventoryEndpointIT
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.222 sec - in it.io.openliberty.guides.inventory.InventoryEndpointIT

Results:

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
----

== Deploying a new version of system microservice

Optionally, you might want to make changes to your microservice and redeploy the updated version. In this section, you will bump the version of the `system` microservice to `2.0-SNAPSHOT` and redeploy the new version of the microservice. 

Use Maven to repackage your microservice:
[role=command]
```
mvn package
```

Next, build the new version of the container image as `2.0-SNAPSHOT`:
[role=command]
```
docker build -t system:2.0-SNAPSHOT system/.
```

Since you built a new image, you need to push it to the repository again. In the following `docker` command, remember to replace `us.icr.io` with your registry and `guide-namespace` with the namespace you created earlier in the guide.

// Tagging images
Tag your container image with the relevant data about your registry.

[role=command]
```
docker tag system:2.0-SNAPSHOT us.icr.io/guide-namespace/system:2.0-SNAPSHOT
```

// Pushing images
Push your image to the registry.

[role=command]
```
docker push us.icr.io/guide-namespace/system:2.0-SNAPSHOT
```

Update the `systemapp` application on IBM Cloud Code Engine to the new container image that you just pushed to the registry:

[role=command]
```
ibmcloud ce app update --name systemapp --image us.icr.io/guide-namespace/system:2.0-SNAPSHOT --registry-secret guide-registry --port 9080
```

Get the `systemapp` url:

[role='command']
```
ibmcloud ce app get --name systemapp --output url
```


// =================================================================================================
// Tear Down
// =================================================================================================

== Tearing down the environment

When you no longer need the serverless microservices, you can delete them from IBM Cloud Code Engine, and all the resources you created in order to deploy the microservices.

Delete the applications from IBM Cloud Code Engine by running the `ibmcloud ce app delete` command:
[role='command']
```
ibmcloud ce app delete --name systemapp
ibmcloud ce app delete --name inventoryapp
```

Delete the project in which the applications were created in IBM Cloud Code Engine:
[role=command]
```
ibmcloud ce project delete -n guide-project
```

Remove your images from your container registry. Remember to replace `us.icr.io` to your registry and `guide-namespace` with the namespace you created earlier in the guide.

[role=command]
```
ibmcloud cr image-rm us.icr.io/guide-namespace/system:1.0-SNAPSHOT
ibmcloud cr image-rm us.icr.io/guide-namespace/system:2.0-SNAPSHOT
ibmcloud cr image-rm us.icr.io/guide-namespace/inventory:1.0-SNAPSHOT
```

Remove the namespace you created in your container registry.

[role=command]
```
ibmcloud cr namespace-rm guide-namespace
```

Log out of your container registry. Remember to replace `us.icr.io` to your registry.

[role=command]
```
docker logout us.icr.io
docker logout registry.ng.bluemix.net
```

Log out of the `ibmcloud` command line tool.

[role=command]
```
ibmcloud logout
```

// =================================================================================================
// finish
// =================================================================================================

== Great work! You're done!

You just deployed two microservices to IBM Cloud Code Engine. You also learned how to use the `docker push` command to push your docker images into IBM Cloud Container Registry, from where you deployed the microservices into Code Engine.

// Multipane
include::{common-includes}/attribution.adoc[subs="attributes"]

// DO NO CREATE ANYMORE SECTIONS AT THIS POINT
// Related guides will be added in automatically here if you included them in ":page-related-guides"
